### ISSUE TITLE
Run Binder Feedback Mini-Workshop at CollabW22

### ISSUE THREAD

**Issue by sgibson91** [sgibson91/ssi-fellowship#33]
### Summary

To begin enacting on the new direction for the Fellowship (#32), we could pilot an early version of a survey during a mini-workshop at [Collaborations Workshop 2022](https://software.ac.uk/cw22).

> **Mini-workshops and demo sessions:** Do you want the opportunity to give an in-depth look at a particular tool or approach related to the CW22 themes and a chance to query developers and experts about how this might apply to participants' areas of work? Are you interested in running a 30-60 minute session to demonstrate a particular software product, approach or standard? Deliver specific training or an interactive tutorial? **Conduct information gathering** or explore a topic? Or another idea?

This would be a very focussed group of people in SSI's network but would provide a range of input across career stage, domains and languages.

### Task List

_These are not necessarily presented in the order they need to be completed and may have interdependencies (i.e. one can't be completed before another)_

**Pre-workshop:**

- [ ] Find collaborators
- [ ] Come up/write session title, abstract and description for submission
- [ ] Decide on 30 min or 60 min session
- [ ] Decide what questions/discussion points do we want to include
- [ ] Decide how to present the questions/discussion points and how answers/feedback will be given
  - I've seen [Mentimeter](https://www.mentimeter.com/) work well for similar information gathering workshops 

**Post-workshop:**

- [ ] Collate and analyse results
- [ ] Disseminate results
  - Blog?
- [ ] Refine the survey questions for a broader round of data collection
  - E.g. Linking from mybinder.org to advertise
  - Would probably **not** use Mentimeter for the second round

---

- **Application form:** https://docs.google.com/forms/d/e/1FAIpQLSf6ZM7N3FLr-_cZJuYF-dvnM0841bRpIGxFn-F5VmqZFALsKw/viewform
- **Deadline:** 🔥  **Friday 4th February 2022, 23:59 GMT** 🔥 
- **Notification of Acceptance:** 18th February 2022
- **Conference:** Monday 4 April - Thursday 7 April 2022 _(online)_

**Comment by sgibson91** [comment]
Quick ping of @meagdoh @RaoOfPhysics and @minrk who all expressed interest in collaborating on this - THANK YOU!

We'll be a multi-national team so I think convening on this issue to share info would be a good bet. I've also invited you all to the repository as collaborators so you can feel free to create new issues as we begin to work on this.

I'm also not sure if y'all know each other either so feel free to say hi and why you're interested in collaborating!

**Comment by RaoOfPhysics** [comment]
Do you have, from logs on mybinder.org for example, an idea of the proportion of those using the service for Python, R, Julia etc.? My instinctive suspicion is that useRs won’t make up big numbers.

The reason I ask is that familiarity with the availability of the tools and their potential may vary across the different groups.

We should probably involve the people behind e.g. https://karthik.github.io/holepunch/ and https://noamross.github.io/gams-in-r-course/ (Intentionally not tagging them so as not to spam them.)?

**Comment by RaoOfPhysics** [comment]
(Also, hello @meagdoh and @minrk!)

**Comment by sgibson91** [comment]
We can get numbers of repo launches and maybe from there work out what languages they are by looking at what config files are present. @minrk I don't know if that would be something related to the repo2docker study you did?

Though tbh, I thought a much simpler approach would be to have Q1 be "Which languages do you use with Binder? Please select all that apply" 😁 The reason I think CW is a good place to pilot this is because I know there are R users who know of/like/use binder in the SSI community. (I admit, Julia may be a trickier community to target.)

**Comment by minrk** [comment]
@vildeeide did some exploration of the launch archive in https://github.com/Vildeeide/repo2docker-reproducibility last year.

I think you can perhaps use the events archive plus a short-circuit of repo2docker to just call BuildPack.detect() to classify each repo by BuildPack at least, and, maybe peek in a little bit for the few buildpacks (conda) that can produce multiple language environments.

One audience-dividing question to start off, might be:

- do you know about Binder?
- do you use Binder?

and then proceed with a line of questioning from there. Because there are 3 broad categories of survey audiences, I think: 

1. use binder, have active user feedback
2. know about binder, don't use it for reasons we might like to know
3. don't know about binder, can ask questions about needs/desires without prejudice!

**Comment by RaoOfPhysics** [comment]
Yeah, I think audience-dividing might be the way to go. I still feel that because of the close coupling of Jupyter {Notebooks,Lab} and Binder, and also Jupyter and Python, Binder may not even be on the radar of the R community, largely because use of notebooks differs quite fundamentally between Jupyter and R Notebooks. Not sure I’m making much sense, and I regret not discussing this when we met, Sarah!

**Comment by sgibson91** [comment]
I get you! I think there definitely isn't as much use of R with Binder as Python, but I also think it's not none. At least from my own experience of running tutorials and giving talks, including at eRum in 2020. And that's part of why what I want to do here is so important! What could get it on their radar? If it is on their radar and they don't use it, why? If they do use it, what's hard about using it? I think at SSI, the ratio of R users to people who have at least heard about Binder is higher than in the wider-community, again why I think this will be a good pilot.

I actually think the Julia community will be way more difficult to target than the R community as they seem to have branched off from Jupyter-like tools much earlier and invested in their own tooling.

**Comment by RaoOfPhysics** [comment]
Yup, with you there. :) Sadly, I have no experience with the Julia community so am not very helpful on that front.

**Comment by sgibson91** [comment]
As an update, I'm going to start working on a draft abstract in #34

**Comment by sgibson91** [comment]
@minrk @RaoOfPhysics @meagdoh I would like to host a little design sprint in the first couple of weeks of March in order to plan out exactly what we hope to learn from this survey, and which questions we should ask to uncover that information. That should then give me two more weeks to create the survey in Mentimeter ready for the workshop (assuming we're accepted! Though this is going towards my fellowship, so it's work I need to do regardless.)

Can y'all please provide availability in the when2meet: https://www.when2meet.com/?14490188-FO37a Since Meag in based in the US, I've gone for European afternoon times. I'm hoping we could find maybe a 2 hour slot to get together?

**Comment by sgibson91** [comment]
Thank you everyone for filling out the when2meet! I've sent out invites with more details on what I hope we can achieve during this sprint. Copied below for reference.

---

First of all, thank you everyone for agreeing to this sprint and filling out your availability. This isn't a perfect slot since y'all are so wonderful and therefore busy. So just to be explicit from the start: if you need to step away for any reason, or this overlaps with a meal time and you've brought your food, that is all okay!

The goal of this sprint is to brainstorm together what we hope to learn from running this survey, some questions for the survey, and any prompts and follow-ups that can encourage discussion during the workshop. I will then take the time to transform these ideas into the survey itself. We already reached consensus in the GitHub Issue that splitting our audience into three tracks would be beneficial, and so we'll need three tracks of questions to uncover the key information these groups can provide (I'm sure there'll be some overlap as well).

We'll be using a tool called [Miro](https://miro.com/) for this sprint that mimics a sticky note style of idea generation. I have setup a board for us to work on already. If you have not used Miro before, you can watch a short introductory video here: https://www.youtube.com/watch?v=7L1-0DOGHDY

**Please sign up for Miro (it's free!) and join the board using this invite link:** https://miro.com/welcomeonboard/M244QVJPVXdoRVJJNU5TVVFrTHhsR1AzUmw4ZGFqaHRBMEdNN3VxSDZhaFY5N2dvRU01SHRuYmdlRVFkOG1BQ3wzNDU4NzY0NTE0NDAxMDkxNjYy?invite_link_id=918854945426

I will run the workshop survey in [Mentimeter](https://www.mentimeter.com/) which can provide live visualisations of responses. So I would like us to think about key questions that can be visualised easily, and then what prompts and follow-ups can we ask about that visualisation to encourage discussion that we will capture in a shared document.

I hope that all makes sense and I look forward to sprinting with you all!

**Comment by sgibson91** [comment]
Woohoo! We were accepted!

**Comment by sgibson91** [comment]
Excerpt of the e-mail below. I've confirmed with Rachael that I'll be in attendance to host, we just need two others to host breakout rooms. @RaoOfPhysics you mentioned you'd be available, are you still happy to do that? @minrk @meagdoh, no pressure to attend if it's inconvenient, I'm fairly confident that the overlap of my network with people who will attend and would be willing to help us out by hosting a facilitated discussion is non-zero 😉 

---

Thank you for submitting a proposal to facilitate a mini-workshop or demo session at Collaborations Workshop 2022 (CW22, https://bit.ly/ssi-cw22) titled "Crowdsourcing Community Practices for Reproducible Computational Environments in the Cloud" - I am delighted to let you know that the session has been accepted!

The session has been tentatively scheduled for CW22 Day 2: **Tuesday, 5 April 2022 from 14:25 - 15:25 BST (13:25 - 14:25 UTC; 60 minutes)**, you can view the full agenda here: https://bit.ly/ssi-cw22-agenda

**Comment by minrk** [comment]
Yay! I'm happy to be available, I think that time slot will work fine for me.

**Comment by RaoOfPhysics** [comment]
I’ll be there! :)

**Comment by meagdoh** [comment]
I'll be there, too!

**Comment by sgibson91** [comment]
IMPORTANT: In case you've not been following the e-mail thread, we have a new day and time slot for the workshop **CW22 Day 3: Wednesday, 6 April 2022 from 10:45 - 11:45 BST (9:45 - 10:45 UTC)**

**Comment by sgibson91** [comment]
## Survey Design Sprint - 2022-03-10

### Notes

-
-
-

### Action Points

-
-
-

**Comment by sgibson91** [comment]
> Think about ways that we can distinguish between users and non-users of Binder in the GDocs without people identifying themselves. Ask people to preface their comments with an emoji?

A note on this, Yo Yehudi is also running a workshop only collaborative note-taking docs specifically for CW participants/workshop hosts, so I can get their opinion when I attend the session next Friday

**Comment by sgibson91** [comment]
I just submitted a funding request to the SSI to cover a small conference plan for Mentimeter: https://www.mentimeter.com/plans/conference This will give us 30 days access to all features of Mentimeter for up to 4 presenters, which is pretty much perfect for what we need!

**Comment by sgibson91** [comment]
I compiled the questions from yesterday into a Google Doc so they're a little easier to read: https://docs.google.com/document/d/14Xv_PfkD-Cn087-rk39iIt3_HoVSxfh1tl-kanxNvYw/edit?usp=sharing

Please feel free to provide edits/comments and move things around if you don't feel like something fits

**Comment by sgibson91** [comment]
> I just submitted a funding request to the SSI to cover a small conference plan for Mentimeter: [mentimeter.com/plans/conference](https://www.mentimeter.com/plans/conference) This will give us 30 days access to all features of Mentimeter for up to 4 presenters, which is pretty much perfect for what we need!

Approved! 🎉

**Comment by sgibson91** [comment]
> * Write up a Participant Information Sheet which includes a GDPR statement

I emailed the SSI regarding GDPR statements and they gave me this link which we are free to copy and amend for our needs. This did raise an interesting discussion though.

> It’s an interesting question about whether your survey falls under the SSI policy. I would suggest that it does not unless we were involved somehow (e.g., co-production) and that us supporting the work was not sufficient for us to be responsible for the data collection / privacy (in the same way funders are not but institutions are). If you are doing this as part of your day work (even though it’s supported by SSI) I think it would have to sit in the wider context of your institution.

Which raises two issues:

- I'm not convinced I belong to an "institution" anymore
- JupyterHub/repo2docker/Binder don't really belong to an institution either (maybe NumFOCUS?)

@choldgraf and I already agreed that this work would count towards the CZI grant for JupyterHub Community Strategic Lead  work, so would CZI be the "institution" in question here.

**Comment by sgibson91** [comment]
> > Think about ways that we can distinguish between users and non-users of Binder in the GDocs without people identifying themselves. Ask people to preface their comments with an emoji?
> 
> A note on this, Yo Yehudi is also running a workshop only collaborative note-taking docs specifically for CW participants/workshop hosts, so I can get their opinion when I attend the session next Friday

Feedback on this from the session.

- Using emojis is a good idea, but need to form a strong association between each attendee and their emoji so that they remember to use it correctly
- Current plan is this:
  - Use an icebreaker/roll call section in the main Google Doc where each attendee will assign themselves an emoji based on their experience with Project Binder
  - We reinforce this question using the first question in the Mentimeter survey
    - Mentimeter allows us to add images to multiple choice questions, so we can provide the visual association too
    - We can then use the first question to sement the results as we see fit
  - In a notes document, we ask the attendees to preface their additional comments with their assigned emoji, repeating what they mean at the top of the doc

**Comment by sgibson91** [comment]
@minrk @meagdoh @RaoOfPhysics 

### Action Points

Please provide any feedback on the following items before **end of day Thursday 31st March**. I will spent Friday making sure everything is ready before the conference kicks off next Monday.

* Please review the following documents and make sure you are happy/understand. They either have comment or full edit access.
  * Facilitator's Guide: https://tinyurl.com/cw22-mw22-facilitators-guide
  * Main Google Doc: https://docs.google.com/document/d/1FQY7nJFlzWcZrqdfQCcCQCxhnTZOgFWnM439aGqBE3Q/edit
  * Intro slides: https://tinyurl.com/cw22-mw22-intro-slides
  * Participant Information Sheet: https://tinyurl.com/cw22-mw22-participant-info
  * Privacy Policy: https://tinyurl.com/cw22-mw22-privacy-policy
  * Shared notes for break-out groups (will duplicate when we're happy): https://tinyurl.com/cw22-mw22-breakout-group-1
  * Feedback form: https://tinyurl.com/cw22-mw22-feedback-form
* Please review the Mentimeter survey (will duplicate when we're happy). You should have received emails to i) join a team, ii) have collaborator access to the presentation - let me know if that's not the case. Let me know if there are any particular questions you feel uncomfortable talking through and why you feel stuck on them. I will try to add speaker's notes to those slides to provide guidance.
  * https://www.mentimeter.com/s/713e9c800344bf1ea557643b9ce3436b/33a7288bf0ed/edit

**Comment by sgibson91** [comment]
@minrk @meagdoh @RaoOfPhysics We are just two days away!!!

- Date/time of the session is **Wednesday 6th April, 10:45-11:45am BEST** ([or your timezone](https://arewemeetingyet.com/London/2022-04-06/10:45/CollabW22%20Mini-Workshop))
- Everything you need to know should be in the facilitators guide: [tinyurl.com/cw22-mw22-facilitators-guide](https://tinyurl.com/cw22-mw22-facilitators-guide)
- If you've signed up to the conference, you'll be receiving emails with links. Otherwise, I believe the zoom link will be added to the main doc provided by the SSI: https://docs.google.com/document/d/1FQY7nJFlzWcZrqdfQCcCQCxhnTZOgFWnM439aGqBE3Q/edit

**Comment by sgibson91** [comment]
@minrk @RaoOfPhysics @meagdoh I want to say another huge thank you for helping me plan and facilitate the session today! 🙏🏻 ❤️ I will close this issue now and have opened up the following issues to track the next steps

- #36 
- #37 
- #38

**Comment by RaoOfPhysics** [comment]
Great job with setting everything up so well for the session!
